### ISSUE TITLE
建议 120.195.190.0/24 整段封禁

### ISSUE THREAD

**Issue by qillme** [PBH-BTN/BTN-Collected-Rules#11]
最开始只有120.195.190.35和120.195.190.34，然后开始每天增加两三个ip。调查发现整个/24段都是快手cdn

**Comment by Ghost-chu** [comment]
BTN-Collected-Rules 并非 PCDN 清单，我们的主要受众是 BT 用户，如果特定地址段没有危害 BT 网络健康，则不会被列入清单。

**Comment by Ghost-chu** [comment]
建议：下次出现此情况时，手动将对应 IP 地址添加到配置文件黑名单，或自行维护一份订阅规则以快速响应。
