### ISSUE TITLE
（严重）多播重复下载IP汇报

### ISSUE THREAD

**Issue by yuricon** [PBH-BTN/BTN-Collected-Rules#14]
![屏幕截图 2024-08-16 233653](https://github.com/user-attachments/assets/15599023-faa7-4b6b-a39b-22c259d05192)
BPH禁封速度没跟上，很多种子多IP同时吸，下完再重下才触发进度重置，已经被吸了30多G，把下面IP段丢到QBEE的banip.dat才止住
36.250.241.0-36.250.241.255

**Comment by Ghost-chu** [comment]
感谢反馈。受限于 BitTorrent 诞生之初的协议设定，以及下载器的 WebUI，在 IP 出现异常之前，PBH 无法做出任何操作。除了协议本身简单，易于伪装和利用以外，下载器 WebUI 提供的数据也相当有限。  
出现此情况时，建议您连接到 BTN 服务器，以便向我们提交 IP 样本数据。在数据提交后我们会定期更新 IP 规则，帮助其它用户拦截这些 IP 地址。正如您的图中所示，其他用户提交的 IP 数据已经帮您拦截了大量异常 IP 地址。这些规则并非空穴来风就会有的，都是其他人的被吸后 PBH 报告异常后上传的数据汇集而成的。  

请避免使用`（严重）`之类的标题字眼，并使用预设问题报告模板，下次将直接关闭 Issue。
