### ISSUE TITLE
伪装主流客户端的节点是否有收集？

### ISSUE THREAD

**Issue by SeaHOH** [PBH-BTN/BTN-Collected-Rules#16]
如题，有一些伪装成 Aria2、qBittorrent 的节点，虚假进度，一直吸。
仓库主页分类似乎没有相应的类别，请问当前是否有收集此类节点呢？

**Comment by Ghost-chu** [comment]
由于其伪装特性难以和正常客户端区分（而且实际上 PBH 也无法区分出此类客户端），因此此类封禁由以下多个文件负责：

* multi-dial.txt - 如果吸血者使用大量相同子网的 IP 吸血，那么会被归入此文件，由人工整理
* untrusted-ips.txt - 其它情况，会由 Sparkle 服务器根据 BTN 客户端上报的结果，动态封禁 IP 地址。对于这种情况，会归入这个文件
