### ISSUE TITLE
建议封禁下列整段ip

### ISSUE THREAD

**Issue by jinyiwei2012** [PBH-BTN/BTN-Collected-Rules#21]
每天大概有20多个封禁，怀疑为多播，均下载同一文件，端口均为22223
标题写不下了
112.20.156.0/24
112.20.152.0/24
112.20.158.0/24
112.20.144..0/24
112.20.146.0/24

**Comment by Ghost-chu** [comment]
看了一下，这些 IP 段都已经在封禁列表里了。

![image](https://github.com/user-attachments/assets/b1b172d6-1029-40f2-83a6-4db2abc72d6f)

只要您在使用 PeerBanHelper 且连接到 BTN 服务器，在 PBH 封禁异常 IP 地址后，会定期上报到 BTN 服务器。  
Sparkle 会根据上报信息自动更新仓库中的规则，我们也会每隔 3 天进行一次人工分析。
