### ISSUE TITLE
建议封禁ip

### ISSUE THREAD

**Issue by PowerfulRichard** [PBH-BTN/BTN-Collected-Rules#25]
建议封禁浙江温州电信机房全部ip，这些ip基本上是刷20-50gb电影，一直重复下载，手动封禁单独ip则会切换另一个ip下载
```
220.190.53.0/24
220.190.31.0/24
220.190.25.0/24
220.190.18.0/24
220.190.15.0/24
220.186.125.0/24
218.71.62.0/24
218.71.23.0/24
218.71.8.0/21
183.130.195.0/24
183.130.21.0/24
125.110.82.0/24
125.109.102.0/24
115.235.153.0/24
115.222.157.0/24
```
以上皆为被我拦截过的ip段

**Comment by Ghost-chu** [comment]
感谢您的反馈，本仓库的规则是由 Sparkle 自动维护 + 人工手动维护。
因可信原因，我们暂不接受单独报告的 IP 地址段（特别是没有提供任何证明其IP段存在问题的资料的）。同样，我们也不接受任何与白名单相关的请求。

如果您有兴趣贡献本仓库的内容，请考虑加入 BTN 网络以提交数据。
