### ISSUE TITLE
逮到一组刷pcdn下载流量的ip，希望可以把子网加到规则里面去

### ISSUE THREAD

**Issue by 1391189216** [PBH-BTN/BTN-Collected-Rules#29]
![image](https://github.com/user-attachments/assets/7c14ecf8-e328-4228-88a3-23635c50cb40)
同一网段，屏蔽了继续换ip
![image](https://github.com/user-attachments/assets/a169f014-f01a-482a-b879-e30833f6bd4d)
我的文件大小2.59G

现在有一个问题：就是诸如Taipei-Torrent dev (n/a)；gopeed dev这些客户端，本来就是正常的客户端，只不过用户少，所以相对来说pcdn刷流量的比例就比较大，以至于让大家以为这些客户端从诞生开始就是用来刷流量的，其实并不是。（顺便说一句，采取一刀切的方法是否对这些客户端的开发者不公平？因为这些客户端如果连接不到bt网络的话，这些作者就没办法开发下去了）

当然，我想反馈的问题是：Taipei-Torrent dev (n/a)；gopeed dev等客户端被一刀切，我发现现在刷流量这有了新的策略，就是反其道而行，这些客户端会直接被pbh封禁，也就是说，pbh不会分析这些客户端的流量，那么他们的ip就永远不会共享到btn网络（这一点从btn的订阅量已经降至3000+可以说明），这种反其道而行的方式，虽然还是有被封的可能，但是他们的目标现在指向的是只订阅了btn规则，却没有安装pbh的部分用户，这部分用户如果不手动在设置里屏蔽这部分客户端，那么就会遭到吸血。

我的想法是，不管是出于公平对待Taipei-Torrent dev (n/a)；gopeed dev等客户端，还是封禁吸血ip的目的，都应该取消掉一刀切的屏蔽策略。另外，诸如迅雷等客户端也应该按照版本来评估是否屏蔽，据我所知，如XunLei0100就是既会正常上传也会正常做种的版本。

**Comment by Ghost-chu** [comment]
> 诸如Taipei-Torrent dev (n/a)；gopeed dev这些客户端，本来就是正常的客户端，只不过用户少，所以相对来说pcdn刷流量的比例就比较大，以至于让大家以为这些客户端从诞生开始就是用来刷流量的，其实并不是

是的，我知道。我不在乎它是否原本是正常的客户端。如果本来就没人用，而且还被刷流量，那它在客观事实上和为刷流量而生没有任何区别。

> 顺便说一句，采取一刀切的方法是否对这些客户端的开发者不公平？因为这些客户端如果连接不到bt网络的话，这些作者就没办法开发下去了

开发的时候可以临时换 ClientName 和 PeerID。

> pbh不会分析这些客户端的流量，那么他们的ip就永远不会共享到btn网络（这一点从btn的订阅量已经降至3000+可以说明）... 

会分析，普通封禁也会上传 BTN 网络，订阅量的下降只是因为合并了段，所以现在精简了很多。我们对于可以简单过滤的客户端不生成 IP 规则。IP 规则并不是越多越好，由于 IP 会更换，因此可能出现误伤。

> 但是他们的目标现在指向的是只订阅了btn规则，却没有安装pbh的部分用户，这部分用户如果不手动在设置里屏蔽这部分客户端，那么就会遭到吸血。

QBEE 和 BitComet 都有 PeerID 和 ClientName 过滤器，如果用户都知道使用 BTN-Collected-Rules 了，那么显然它们也应该知道如何正确设置下载器。(并且 PBH 也支持 BitComet 或者 qBittorrent)  
BTN-Collected-Rules 首要任务是为 PeerBanHelper 分流规则，对公共提供服务是附加的。  

对于这种固定 IP 地址吸血的，后续也许可能会考虑添加到列表中。

> 都应该取消掉一刀切的屏蔽策略

目前没有更好的办法。我的首要任务是保证正常 BT 用户不被吸血到签保证书，而不是为了少数人牺牲大多数人的利益。

> 诸如迅雷等客户端也应该按照版本来评估是否屏蔽

由于 https://github.com/PBH-BTN/PeerBanHelper/issues/254 ，因此最近一年内我们都不会再考虑给迅雷机会了，并且[我们知道哪些迅雷是有上传的](https://github.com/PBH-BTN/quick-references/blob/main/xunlei_proof.md)。

**Comment by 1391189216** [comment]
> > 并且[我们知道哪些迅雷是有上传的](https://github.com/PBH-BTN/quick-references/blob/main/xunlei_proof.md)。

这个名单里似乎少了一项判断标准，0019等等虽然会上传，但是只会在下载阶段上传，一但100%就会停止上传，也就是说0019不会做种。只在下载阶段上传，即便上传不限速，不做种的话也是一种变相吸血行为。目前仅仅只有xunlei0100才会做种，也只有xunlei0100才是真正意义的不吸血。当然，可以在做种阶段断开0019的连接以作为反制。

**Comment by Ghost-chu** [comment]
> Refere

我不在乎 0019 还是 0100，重要的是我们已经给过迅雷机会了，迅雷没有抓住。在迅雷被屏蔽了这么多年的时间里，PBH 作为同类反吸血软件是首个愿意尝试将迅雷从默认列表中移除的软件。但我们得到的只是低到无法入眼的分享率。  

在过去这么多年的时间里，迅雷已经足够破坏 BT 环境了，现在看着它人畜无害只是因为全靠同行衬托。**如果有人愿意给迅雷上传，他们完全可以自己删除对迅雷的屏蔽规则。没有人阻止用户这样做，而且确实已经有人正在这样做了。更多人只是默认的讨厌迅雷所以保持了默认的规则没有作出改动。**

我认为继续讨论这些毫无意义的话题完全是在浪费时间，你我的时间都很宝贵，不如用在其它更有价值和有意义的地方。
