### ISSUE TITLE
My host address is incorrectly marked as "high risk ip".

### ISSUE THREAD

**Issue by MasahinaAfuyu** [PBH-BTN/BTN-Collected-Rules#30]
It is a IDC host. I use it because my home ISP provides poor connectivity. Even though it has normally uploaded a lot, it is marked as "high risk", which I think makes no sense. I am wondering if there is a list of criteria in how a peer seems risky.

**Comment by Ghost-chu** [comment]
High Risk IPs are automatically flagged by other PeerBanHelper users and are listed as high risk ips if you have been banned for Progress AntiCheat by more than one user and the threshold is reached.

If you download a seed within 45 days and delete and restart the download after completing/partially downloading it, or use Super Seeding (we'll address this in the future), it will be flagged as a one-time violation.

**Comment by Ghost-chu** [comment]
In particular, you may also be flagged as high risk if you use a less reputable (meaning recently abused on the network) client.

For this month it's Transmission 2.94/3.00 (which abused by companies running PCDN nodes for pointless loop downloading) and aria2 (same as above)

**Comment by Ghost-chu** [comment]
If you believe that your IDC Host has been incorrectly blocked, please provide the IP address in comment  and we will manually verify it.

**Comment by Ghost-chu** [comment]
The detection algorithm has been optimized for the current live environment, please check again to see if it is still on the list.

**Comment by MasahinaAfuyu** [comment]
I am very grateful for your kindness. I have removed a torrent and started it again. The criteria seem sensible indeed to me.
﻿
The address remains on the list, but it is okay for me to wait for some days and not to bother with that.
