### ISSUE TITLE
发现新的IP段

### ISSUE THREAD

**Issue by f1ume** [PBH-BTN/BTN-Collected-Rules#32]
Client ID有anacrolix字眼，没有Peer ID
![anacrolix](https://github.com/user-attachments/assets/9650cda8-59e3-421f-a4a7-1cf0a6d3ed5b)

另外，还发现一个新的疑似客户端
这里有个和我一样的
[这里](https://meta.appinn.net/t/topic/63956)
Client ID: ydownloader/1.0，Peer ID: A2-1-0--
ydownloader搜索出是下油管视频的，总不会拿来下bt吧
希望确定一下

**Comment by f1ume** [comment]
又有新的，这次截到更直观的图
![2](https://github.com/user-attachments/assets/5c7ad974-7a2d-4b28-ba2b-3c110d30ab59)

**Comment by Ghost-chu** [comment]
gateway 该 UA 目前来看是没有异常的。

101.199.254.0/24 下面没有封禁报告。

提示：qb 在连接某个 IP 时，无论 IP 是否有效，是否可以连接，qb 都会将其显示在用户列表中。上图只能说明有人给你了这个 IP 并且你在尝试连接对方。IP 过滤器会在连接时就直接切断链接，无论是否成功日志都会打印。

**Comment by f1ume** [comment]
> gateway 该 UA 目前来看是没有异常的。


可是Peer ID是未知。这绝对是故意隐藏了

**Comment by f1ume** [comment]
> gateway 该 UA 目前来看是没有异常的。

原来第二个ip段之前有人报过。
/issues/22  同一段，
我的帖的两个iP段都是连的
同一个种子。
同一个Client ID。
同样没有Peer ID。
同一时间出现同一个C段。
几个原因加起来我才会怀疑
