### ISSUE TITLE
汇报疑似新IP段

### ISSUE THREAD

**Issue by TomoeMami** [PBH-BTN/BTN-Collected-Rules#33]
> 对方可能是部署了新的客户端，显示QT某个固定的版本，下载进度也正常，没什么明显特征。我发觉不正常，是因为有连续的IP用同一个版本的客户端反复下几个文件。
> 这是我手工ban掉的IP段
> ::ffff:124.91.148.0-::ffff:124.91.148.255
> 124.91.148.0-124.91.148.255
> 1.58.198.0-1.58.198.255
> 112.82.223.0-112.82.223.255
> 112.82.234.0-112.82.234.255
> 153.35.236.0-153.35.236.255
> 122.96.244.0-122.96.244.255

[来源](https://bbs.saraba1st.com/2b/forum.php?mod=redirect&goto=findpost&ptid=2178719&pid=66962272)

**Comment by Ghost-chu** [comment]
> 112.82.223.0-112.82.223.255
> 112.82.234.0-112.82.234.255

没有封禁报告

> ::ffff:124.91.148.0-::ffff:124.91.148.255

感谢汇报，已核实该 IP 段刷流情况，并更新到规则

> 1.58.198.0-1.58.198.255
> 153.35.236.0-153.35.236.255
> 122.96.244.0-122.96.244.255

没有封禁报告
