### ISSUE TITLE
all.txt 大量IPv6異常

### ISSUE THREAD

**Issue by thrive7776** [PBH-BTN/BTN-Collected-Rules#35]
1. 尾巴"/XX"不見了
>2001:240:28e8:4000::
2001:250:209:2000::
2001:250:209:6500::
2001:250:1001:2500::
(～略～)

2. 承上，終端用戶最小分配單位是/64，
封單個IPv6/128約等於沒封，何況標題寫的56？？？
># [START] Auto merged CIDR - IPV4: 24, IPV6: 56     ←
>2001:250:3c00:3565:2923:bcaf:eb84:cf7a
2001:250:4000:8019:104d:ca76:b382:de36
2001:da8:801d:72ef:808d:31ff:fef1:621a
2001:da8:c003:2995::2:ceaa
(～略～)

**Comment by Ghost-chu** [comment]
@paulzzh 看看

**Comment by paulzzh** [comment]
合并器按预期工作
这里合并指的是，同一个/56段下，存在>=3个不同ip（举例：存在4个/64被封禁 或者 存在3个/128），那么封禁整个/56
![image](https://github.com/user-attachments/assets/2e11c835-0f0c-4fba-b3a5-4cfa0080ef68)

**Comment by thrive7776** [comment]
抱歉，廢話太多分散了重點，
兩點都在強調「收錄單個IPv6的不合理」。

第1：缺少"/XX"，就是後綴為0的單個IPv6。
例如strange_ipv6_block.txt；
本來最小都有/60的，更新後突然就無了。
https://github.com/PBH-BTN/BTN-Collected-Rules/commit/a14b45464cb856df81eb0ae6da53b0fb5d874613

第2：展開的IPv6，應收斂至/64或/60。
