### ISSUE TITLE
汇报几个ip

### ISSUE THREAD

**Issue by julpage** [PBH-BTN/BTN-Collected-Rules#4]
-GT0003-
223.78.79.65
223.78.79.97
223.78.79.161
223.78.79.193
223.78.79.225
223.78.80.1
223.78.80.33
223.78.80.65
223.78.80.97
2409:873c:f03:6001::ee
2409:873c:f03:6009::ee
2409:873c:f03:600a::ee
2409:873c:f03:6002::ee
2409:873c:f03:6003::ee
2409:873c:f03:6004::ee
2409:873c:f03:6005::ee
2409:873c:f03:6006::ee
2409:873c:f03:6007::ee
2409:873c:f03:6008::ee

还有一些其他ip不确定是否可疑
[来源.txt](https://github.com/user-attachments/files/16026231/default.txt)

**Comment by Ghost-chu** [comment]
感谢楼主的反馈，BTN-Collected-Rules 的数据来自 BTN 网络，由于可信原因，我们暂时不从其它来源获取 IP 数据。

仓库暂时不接受 PR，但我会保持此 Issue 开放，以供他人参考。感谢楼主对维护 BitTorrent 环境做出的贡献。

**Comment by Ghost-chu** [comment]
在 2024/07/13 更新的新的规则文件中，检查包含了上述所有 IP 地址。  
https://github.com/PBH-BTN/BTN-Collected-Rules/commit/f1357d272e169bc6f055109eb1e2a657b7473f15

关闭。
