### ISSUE TITLE
建议提供一份所有 IP 的列表

### ISSUE THREAD

**Issue by xddxdd** [PBH-BTN/BTN-Collected-Rules#5]
建议提供一份包含仓库内所有 IP 的列表（例如命名为 `all.txt`），方便添加到 PBH 或防火墙，并且如果有新的分类出现（例如新增的 `gitlab.i.ljyun.cn-hangzhou-monitoring.txt`）不会因为没看到更新而遗漏屏蔽。

**Comment by Ghost-chu** [comment]
感谢建议，现已添加：https://github.com/PBH-BTN/BTN-Collected-Rules/blob/main/combine/all.txt
