### ISSUE TITLE
建议以前缀（地址段）代替IPv6的地址黑名单

### ISSUE THREAD

**Issue by jieyitang** [PBH-BTN/BTN-Collected-Rules#6]
目前的运营商家宽都至少分配了/64的前缀，部分分配了/60或者/56长度。我有观测到连续的/64前缀但后缀完全相同的客户端连接，高度疑似使用PD后分配给了同一台机器。也有随机后缀来规避屏蔽的可能。直接按前缀屏蔽是更好的选择。
另外，IPv4单区域的最长前缀是/24，IPv6单区域的最长前缀是/48，大部分地区的前缀更短（可能是/36，/40等），建议提供一份更大范围屏蔽屏蔽列表。

**Comment by Ghost-chu** [comment]
感谢您的支持。本仓库的规则分为两种：

* 人工整理规则，通常是 CIDR 表示法
* 归纳规则，使用 SQL 从 BTN 中提取，这类规则通常是普通 IP

对于人工整理的规则，已经在使用 /24 /16 /60 进行封禁了。

**Comment by jieyitang** [comment]
家宽的IPv6绝大部分是动态的

> 感谢您的支持。本仓库的规则分为两种：
> 
> * 人工整理规则，通常是 CIDR 表示法
> * 归纳规则，使用 SQL 从 BTN 中提取，这类规则通常是普通 IP
> 
> 对于人工整理的规则，已经在使用 /24 /16 /60 进行封禁了。

**Comment by jieyitang** [comment]
家宽IPv6一般是动态的前缀（尽管我是静态的），所以把家宽的范围扩大到/48或许是合理的范围。至于IPv4，可能需要按/24统计。
不可否认，这样肯定会误伤。
