### ISSUE TITLE
屏蔽机房IP段的可行性？

### ISSUE THREAD

**Issue by mzhboy** [PBH-BTN/BTN-Collected-Rules#7]
最近检测到一个讨厌的客户端，过一段时间就会重置进度，而且相关度为0。如下图

![Snipaste_2024-07-22_03-58-41](https://github.com/user-attachments/assets/3c71ac2d-f74d-437c-9aee-733a92805532)

去查了其IP，发现是一个电信机房。实际上在规则里面也发现了该机房的其他IP。

![Snipaste_2024-07-22_05-04-55](https://github.com/user-attachments/assets/18fd35f9-974c-4e40-8000-5f04be5d778b)

考虑到中国机房带宽很贵，很少用来做BT，是不是可以将某些机房加入黑名单。

**Comment by jieyitang** [comment]
这需要一个准确的IP库做支持。实际上，如果真的能获取一份精准到街道的IP库，就可以精准屏蔽（前提是刷流量并不是分布式的全国的刷）。
三大运营商的IPv6在分配上就是按接入所在地址来分的，所以可以通过多日的数据来猜测刷流量的设备所在区域的前缀，并全部屏蔽，但IPv4不行，分配是乱的。

**Comment by Ghost-chu** [comment]
理论可行。PeerBanHelper 带的 [GeoCN](https://github.com/ljxi/GeoCN) 数据库可识别 9 种 IP 类型，不过目前还不支持按类型封禁，但我觉得这是个很合适提议。

还挺楼主前往 PBH 的 Issue Tracker 打开功能请求：[PeerBanHelper Issue Tracker](https://github.com/PBH-BTN/PeerBanHelper/issues)
