### ISSUE TITLE
汇报疑似恶意下载IP

### ISSUE THREAD

**Issue by TomoeMami** [PBH-BTN/BTN-Collected-Rules#8]
![Snipaste_2024-07-25_00-20-03](https://github.com/user-attachments/assets/05e5aed9-5fa4-4a2f-b6c0-02d443b2fd7c)

![image](https://github.com/user-attachments/assets/38242598-5469-4758-83ea-c85971a1e377)

58.216.63.*，具体网段不清楚，已知如下：

58.216.63.11
58.216.63.13
58.216.63.14
58.216.63.15
58.216.63.20
58.216.63.22
58.216.63.23
58.216.63.24
58.216.63.25
58.216.63.26
58.216.63.27
58.216.63.28
58.216.63.29
58.216.63.30

还有另一个也同样恶意下载，客户端一致为Aria2/1.33.1但IP不同的：
58.216.33.116

**Comment by Ghost-chu** [comment]
感谢报告，情况属实。进行数据库检索后，共有以下多个异常 IP 地址：

```
58.216.33.116
58.216.33.117
58.216.63.10
58.216.63.11
58.216.63.12
58.216.63.13
58.216.63.14
58.216.63.15
58.216.63.16
58.216.63.17
58.216.63.18
58.216.63.19
58.216.63.2
58.216.63.20
58.216.63.21
58.216.63.22
58.216.63.23
58.216.63.24
58.216.63.25
58.216.63.26
58.216.63.27
58.216.63.28
58.216.63.29
58.216.63.3
58.216.63.30
58.216.63.31
58.216.63.5
58.216.63.6
58.216.63.7
58.216.63.8
58.216.63.9

```
